version: '3'

services:
  db:
    container_name: csq-mariadb-server
    image: mariadb:10.5.8-focal
    restart: always
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Csq123
      MYSQL_DATABASE: csq
    ports:
      - 3306:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]