spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {client-id}
            client-secret: { client-secret }
            scope: profile, email

#          naver:
#            client-id: J_rjnOzKr8QstAzgHq2g
#            client-secret: C4qvdIJcDh
#            redirect-uri: http://localhost:8080/login/oauth2/naver
#            authorization-grant-type: authorization_code
#            scope: name, email, profile_image
#            client-name: Naver
#            provider:
#              naver:
#                authorization_uri: https://nid.naver.com/oauth2.0/authorize
#                token_uri: https://nid.naver.com/oauth2.0/token
#                user-info-uri: https://openapi.naver.com/v1/nid/me
#                user_name_attribute: response
